'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabase-browser';

type Appointment={id:string;starts_at:string;status:string;customers:{full_name:string}|null;services:{name:string}|null;profiles:{full_name:string}|null;locations:{name:string}|null};
export default function Dashboard(){
 const [loading,setLoading]=useState(true); const [org,setOrg]=useState<any>(null); const [stats,setStats]=useState({today:0,pending:0,clients:0,occupancy:0}); const [turns,setTurns]=useState<Appointment[]>([]); const [error,setError]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){const db=supabase();const {data:{user}}=await db.auth.getUser();if(!user){location.href='/ingresar';return} const {data:profile}=await db.from('profiles').select('organization_id,full_name,organizations(*)').eq('id',user.id).maybeSingle();if(!profile){setError('Tu cuenta todavia no tiene una empresa configurada.');setLoading(false);return} const organization=(profile as any).organizations;setOrg({...organization,manager_name:(profile as any).full_name});const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const [today,pending,clients,appointments]=await Promise.all([db.from('appointments').select('id',{count:'exact',head:true}).gte('starts_at',start.toISOString()).lt('starts_at',end.toISOString()),db.from('appointments').select('id',{count:'exact',head:true}).eq('status','pending'),db.from('customers').select('id',{count:'exact',head:true}),db.from('appointments').select('id,starts_at,status,customers(full_name),services(name),profiles!appointments_professional_id_fkey(full_name),locations(name)').gte('starts_at',start.toISOString()).lt('starts_at',end.toISOString()).order('starts_at').limit(8)]);setStats({today:today.count??0,pending:pending.count??0,clients:clients.count??0,occupancy:today.count?Math.min(100,(today.count??0)*10):0});setTurns((appointments.data??[]) as unknown as Appointment[]);setLoading(false)}
 if(loading)return <main className="admin-page"><div className="loading-card">Preparando tu agenda...</div></main>;
 if(error)return <main className="admin-page"><section className="empty-onboarding"><p className="brand">PRIMER PASO</p><h1>Configuremos tu empresa</h1><p>{error}</p><button className="primary-button" onClick={async()=>{const {error:e}=await supabase().rpc('bootstrap_organization',{p_name:'Mi empresa',p_full_name:'Administrador'});if(e)setError(e.message);else location.reload()}}>Crear mi espacio de trabajo</button></section></main>;
 return <main className="admin-page"><header className="admin-page-header"><div><p className="page-kicker">RESUMEN GENERAL</p><h1>Hola, {org?.manager_name?.split(' ')[0]||'Emiliano'}</h1><p>Todo lo importante de {org?.name} en un solo lugar.</p></div><a className="primary-link" href="/panel/turnos">+ Nuevo turno</a></header><section className="admin-stats">{[[stats.today,'Turnos de hoy'],[stats.pending,'Por confirmar'],[stats.clients,'Clientes'],[`${stats.occupancy}%`,'Ocupacion estimada']].map(([n,l])=><article className="metric-card" key={l as string}><span>{l}</span><strong>{n}</strong></article>)}</section><section className="dashboard-columns"><article className="surface agenda-surface"><div className="section-heading"><div><span>HOY</span><h2>Agenda del dia</h2></div><a href="/panel/turnos">Ver agenda completa</a></div>{turns.length?<div className="turn-list">{turns.map(t=><div className="turn-row" key={t.id}><time>{new Date(t.starts_at).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</time><div className="avatar-dot">{t.customers?.full_name?.slice(0,1)||'C'}</div><div><b>{t.customers?.full_name||'Cliente'}</b><small>{t.services?.name||'Servicio'} · {t.profiles?.full_name||'Sin profesional'}</small></div><span className={`status status-${t.status}`}>{t.status}</span></div>)}</div>:<div className="empty-state"><b>No hay turnos para hoy</b><p>Cuando ingresen reservas, apareceran aca.</p></div>}</article><aside className="surface setup-surface"><span>CONFIGURACION</span><h2>Completa tu espacio</h2><p>Deja lista la empresa para recibir reservas reales.</p><div className="setup-list"><a href="/panel/empresa"><i>1</i><div><b>Datos de la empresa</b><small>Nombre, contacto y reservas</small></div></a><a href="/panel/profesionales"><i>2</i><div><b>Equipo profesional</b><small>Roles y especialidades</small></div></a><a href="/panel/disponibilidad"><i>3</i><div><b>Horarios disponibles</b><small>Dias y franjas de atencion</small></div></a></div></aside></section></main>
}
