'use client';
import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase-browser';
export default function Ingresar(){
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get('error'))setMessage('No pudimos completar el ingreso. Intenta nuevamente.');if(q.get('estado')==='inactivo')setMessage('Esta cuenta fue desactivada. Contacta al administrador de tu empresa.')},[]);
 function destination(){const value=new URLSearchParams(location.search).get('next')||'/panel';return value.startsWith('/')&&!value.startsWith('//')&&!value.includes('\\')?value:'/panel'}
 async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);const {error}=await supabase().auth.signInWithPassword({email:String(f.get('email')).trim().toLowerCase(),password:String(f.get('password'))});if(error){setMessage('El correo o la contraseña no son correctos.');setBusy(false)}else location.replace(destination());}
 async function google(){setBusy(true);setMessage('');const next=destination();const {error}=await supabase().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent(next)}`,queryParams:{prompt:'select_account'}}});if(error){setMessage('No pudimos iniciar con Google. Intenta nuevamente.');setBusy(false)}}
 return <main className="auth-page"><section className="card auth-card"><a className="muted" href="/">Volver al inicio</a><p className="brand">SACA UN TURNITO</p><h1>Ingresar</h1><p className="muted">Accede de forma segura para organizar o reservar tus turnos.</p><form onSubmit={password}><label>Correo<input required name="email" type="email" autoComplete="email" maxLength={254}/></label><label>Contraseña<input required name="password" type="password" autoComplete="current-password" minLength={8} maxLength={128}/></label><button className="primary-button" disabled={busy}>{busy?'Ingresando...':'Ingresar'}</button><div className="divider"><span>o</span></div><button type="button" className="google" onClick={google} disabled={busy}><span className="google-mark">G</span>Continuar con Google</button>{message&&<p className="message" role="alert">{message}</p>}</form></section></main>;
}
